Level 2
skalolaz2012/movies-explorer-frontend pull request #1
Opened 2023-06-19 16:52 UTC by skalolaz2012

2023-06-19 18:11 UTC, Savallera requested changes
Здравствуйте!

У Вас получилась хорошая работа.

# Резюме по работе:

В комментариях выделена примерная часть замечаний, Вам следует самостоятельно на примере найти и исправить все похожие случаи

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

- https://yadi.sk/d/sO8s7a9ZHfdTBw ошибка указания пути
- https://yadi.sk/d/_GFcYex0f8CCOQ размер иконки на 320
- https://yadi.sk/d/ZNJzZOG5pb4xiw https://yadi.sk/d/_CjTMB2J3Qms7A https://yadi.sk/d/P8gVEDiSyvb3CA https://yadi.sk/i/fxHsoxlw-4rPPQ на страницах 768 и 320 в макете следует удалить минимальную высоту (можно на адаптиве установить в vh) и установить центрирование относительно вьюпорта, чтобы не создавался вертикальный скролл
- https://yadi.sk/d/fzIie3fWGLOq7A https://yadi.sk/d/5u00Nv2WeH5sfg расположение не по макету

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

* https://yadi.sk/d/duYUyYCanzhEHA образуется гор.прокрутка при сужении
* https://yadi.sk/d/y7F5tQ-9oxFw-Q элементы выпадают из род.блока

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* https://yadi.sk/d/Izv8BY8D8ZlR5g https://yadi.sk/d/kcLcyljSsV3V_A, на всех страницах - Элемент без род.блока Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/d/jKWgMA8TqxLBVw https://yadi.sk/d/UBSttOiqO3i6gw следует удалить фиксацию высоты в элементах, содержащих контент или динамику, чтобы блок не ломался, можно использовать мин.высоту
* https://yadi.sk/d/UiHFKfbx8IA_qg при сужении блок следует центрировать по оси X

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- header__container_type..., menu Для оформления навигации используйте семантический тег nav
- https://yadi.sk/d/nJet5IB8LIzYAg Основной контент на страницах оберните семантическим тегом main, также удалите лишний селектор `<b>`
- footer__copyright оформите параграфом для улучшения семантики
- https://yadi.sk/d/lshn_t0t8TFbCA каждой странице нужен заголовок 1 уровня. На странице с фильмами он не предусмотрен по макету, для этого можно главной секции задать aria-label
- burger__container - не навигаиционный список, можно оформить кнопкой
-https://yadi.sk/d/9qGPdtLkRDmHKA главные блоки оформите секциями

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

* page404__button расположите элемент в потоке, без использования абсолюта

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

- https://yadi.sk/d/OiY-FYBhi9B3rg https://yadi.sk/d/iHvn9bsw8jTmlA у полей нет состояния ховера
- https://yadi.sk/d/FHQAUO5bREbsxg нет ховер эффекта

- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

- Поля не редактируемы, также не проходят валидацию обязательные поля.

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 50

## Доп. Комментарии:
- Язык на страницах русский - ru
- Проекту правильно установлена максимальная ширина по макету, также следует установить фоновый цвет секциям по макету, чтобы не было белых полос по бокам на больших мониторах.
- https://yadi.sk/i/jFoMpCKIFrZx8w простые иконки можно реализовать через стилевые описания, для более сложных использовать svg формат, также из проекта можно удалить неиспользуемые изображения.
- обращайте внимание на размер иконок - https://yadi.sk/d/YrTMbRqlmxs-8A данное изображение можно облегчит загрузив через формат png.
- https://yadi.sk/d/sO8s7a9ZHfdTBw https://yadi.sk/d/mVqUB2qbGumgmA декоративные изображения из разметки следует удалить, расположив фоном или на псевдоэлементе.
- https://yadi.sk/d/slfY_svqkbW-Eg метку также можно прикрепить к чекбоксу, чтобы она имела зовер и состояние менялось
- https://yadi.sk/d/FRitf5vqmeaHbQ выглядит как лишняя вложенность, можно удалить без вреда
* https://yadi.sk/d/wVLTaI6o9s4taw див - лишняя вложенность, также можно заголовок секции выделить отдельным блоком по стилизации, т.к. он повторяется.
- search-form__line линию следует стилизовать, удалив из разметки

2023-06-21 08:28 UTC, Savallera requested changes
Здравствуйте!

Готово второе ревью по Вашей проектной работе, много стало лучше, молодец, так держать!

# Резюме по работе:

В комментариях выделена примерная часть замечаний, Вам следует самостоятельно на примере найти и исправить все похожие случаи

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* https://yadi.sk/d/mZvZ5whUsr1oEw 320 высота выпадающиего меню в 100% от высоты вьюпорта

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* https://yadi.sk/d/kF2HagqmAImTcA Сохраняются ошибки по БЭМ. Элементы всегда расположены внутри блока к которому относятся.

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/d/yS1t1NLh-FzKpg https://yadi.sk/d/CVNXeHf1LiIdlg на страницах начал образовываться вертикальный скролл. Установлена фиксация высоты. Контент на таких страницах центрирован относительно вьюпорта, здесь можно использовать правила построения сетки через флеск/грид и выровнять относительно родительского блока. https://yadi.sk/d/sdFS8MQpx9bxZg обратите также внимание, что остались пустые обертки, они не имеют стилевых описаний, от них можно легко избавиться без вреда. Скорректируйте все страницы по аналогии https://yadi.sk/d/Yg4ea7bt3p_IyQ на всех устройствах.
* https://yadi.sk/i/h6M8MleJ9li0bA элементы выпадают из род.блока, кнопке можно дать ширину в % от ширины родителя

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- https://yadi.sk/i/6qAp6JBBJmgiVA Основной контент на страницах оберните семантическим тегом main

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

* https://yadi.sk/d/mOGdlPa4ETYWHA полям не заданы атрибуты placeholder (https://doka.guide/html/placeholder/), также поле не доступно для редактирования и обязательные поля не проходят валидацию (https://developer.mozilla.org/ru/docs/Learn/Forms/Form_validation). Если поле не заполнено/заполнено некорректно, следует указывать статус ошибки, как в макете https://yadi.sk/d/vG5XpZgoukVnfQ

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 68

## Доп. Комментарии:
- https://yadi.sk/d/cZOdbNYBddq7VQ На больших мониторах образуются белые полосы по бокам, можно их избежать, добавив контейнеры с фоновым цветом каждым нужным секциям

2023-06-21 16:25 UTC, Savallera requested changes
Здравствуйте!

Готово третье ревью по Вашей проектной работе.
Появились новые замечания: на странице с Фильмами начал образовываться гор.скролл при сужении, также на страницах вход/регистрация при сужении контент прижимается в левый нижний край, что не соотв. макету.

В итоге, набранного балла не хватает для принятия проекта (нужно 80).
Обращаю Ваше внимание, что итерация у Вас последняя.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

# Резюме по работе:

В комментариях выделена примерная часть замечаний, Вам следует самостоятельно на примере найти и исправить все похожие случаи

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* https://yadi.sk/d/50-ke0DVeUX0pQ фиксируется высота, образуется вертикальный скролл

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

* https://yadi.sk/i/dze0DxcGwWXE7A https://yadi.sk/d/TD1RlXTtxMDqjw При сужении начал образовываться горизонтальный скролл на странице с фильмами, ширина кнопки + паддинги больше вьюпорта вышли.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* https://yadi.sk/d/1tgchNWkKPTt1A Сохраняются ошибки по БЭМ. Элементы всегда расположены внутри блока к которому относятся.

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/i/wCswGJJmQQxHAw вход/регистрацию следует центрировать относительно вьюпорта по двум осям
* https://yadi.sk/i/h6M8MleJ9li0bA элементы выпадают из род.блока, кнопке можно дать ширину в % от ширины родителя

- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

* https://yadi.sk/d/mOGdlPa4ETYWHA полям не заданы атрибуты placeholder (https://doka.guide/html/placeholder/), также поле не доступно для редактирования и обязательные поля не проходят валидацию (https://developer.mozilla.org/ru/docs/Learn/Forms/Form_validation). Если поле не заполнено/заполнено некорректно, следует указывать статус ошибки, как в макете https://yadi.sk/d/vG5XpZgoukVnfQ

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 72

2023-07-02 09:46 UTC, coolswood commented
# Резюме по работе:
## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
`В макете отсутствует такое расположение блоков. Картинка должна находиться сверху`
<img width="932" alt="Screenshot 2023-07-02 at 12 38 30" src="https://github.com/skalolaz2012/movies-explorer-frontend/assets/25247802/bcb482de-1167-4ed2-8bbd-2e32e8ed6f73">


- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
`Появляется горизонтальный скролл на расширении от 470рх и менее (/movies; /saved-movies)`

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открывафются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
`Необходимо проверить валидацию.  Вы можете проверить ее здесь (https://validator.w3.org/)`

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;x
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [x] Разметка портирована в JSX:ф
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для эточго не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [x] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете. 
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
`Св-во novalidate не дает форме завалидироваться (class="search-form__content")`

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 72

## Доп. Комментарии:

2023-07-03 14:44 UTC, coolswood commented
# Резюме по работе:
## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открывафются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;x
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [x] Разметка портирована в JSX:ф
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для эточго не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [x] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете. 
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 100

## Доп. Комментарии:

2023-07-05 15:50 UTC, merged